services:
  collector-service:
    build: ./collector-service
    ports:
      - "8000:8000"
    env_file:
      - ./collector-service/.env
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_REGION=us-east-1
      - EMAIL_NOTIFICACAO=icraftgamer@gmail.com
      - SNS_TOPIC_ARN_EMAIL=arn:aws:sns:us-east-1:985798502313:immunotrack-alerts
      - DEBUG=True
      - LOG_LEVEL=INFO
    networks:
      - immunotrack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/saude"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  sensor-service:
    build: ./sensor-service
    environment:
      - COLLECTOR_URL=http://collector-service:8000
      - SENSOR_ID=sensor-001
      - INTERVAL=10
      - PYTHONUNBUFFERED=1
    networks:
      - immunotrack-network
    depends_on:
      collector-service:
        condition: service_healthy

networks:
  immunotrack-network:
    driver: bridge
